#! /bin/sh

sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

# Border around windows
bspc config border_width         0

# Gaps between windows
bspc config window_gap          12

# Ratio for slitting windows
bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Rule "dropdown" st terminal 
bspc rule -a st-dropdown state=floating
bspc rule -a Pavucontrol state=floating

# bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a Chromium desktop='^2'
# bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off

# Set background with feh
feh --bg-fill ~/E/AlexBecker/Pictures/Wallpapers/whiterun.jpg &

# Start picom for transparency
picom &

# Enable tapping on trackpad
xinput set-prop 12 319 1

# polybar launch script; kills all open polybars and starts main bar
zsh ~/.config/polybar/launch.sh
