#! /bin/sh

sxhkd &

bspc monitor eDP-1 -d 1 2 3 4 5 6 7 8 9 10

# bspc monitor HDMI-1 -d  1 2 3 4 5
# bspc monitor eDP-1 -d 6 7 8 9 10
# # Have to swap for some reason to get it to work right
# bspc monitor HDMI-1 -s eDP-1

# Border around windows
bspc config border_width         2
bspc config focused_border_color  "#00FF9C"
# Dracula color scheme
# bspc config normal_border_color "#44475a"
# bspc config active_border_color "#bd93f9"
# bspc config focused_border_color "#ff79c6"
# bspc config presel_feedback_color "#6272a4"

# Gaps between windows
bspc config window_gap           8

# Ratio for slitting windows
bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true
bspc config pointer_follows_focus true
bspc config pointer_follows_monitor true
bspc config ignore_ewmh_struts false

# Rule "dropdown" st terminal 
bspc rule -a st-dropdown sticky=on state=floating hidden=on
# TODO: Kill running instances of st-dropdown
[ "$(ps -x | grep -c 'st-dropdown')" -eq "1" ] && st -c 'st-dropdown' -e tmux &

# Window rules (mostly floating stuff)
bspc rule -a Pavucontrol state=floating center=true
bspc rule -a Blueman-manager state=floating center=true

# Set background with feh
# feh --bg-fill ~/Pictures/whiterun.jpg &
variety &

# Start picom for transparency
picom &

# polybar launch script; kills all open polybars and starts main bar
zsh ~/.config/polybar/launch.sh

# Enable tapping on trackpad
xinput set-prop 14 321 1

numlockx &
