#! /bin/sh

sxhkd &

if type "xrandr"; then
    for m in $(xrandr --query | grep -w "connected" | cut -d " " -f1); do
        bspc monitor $m -d I II III IV V VI VII VIII IX X
    done
else 
    bspc monitor -d I II III IV V VI VII VIII IX X
fi

# Border around windows
bspc config border_width         2
bspc config focused_border_color  "#0A9504"

# Gaps between windows
bspc config window_gap           8

# Ratio for slitting windows
bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true
bspc config pointer_follows_focus true

# Rule "dropdown" st terminal 
bspc rule -a st-dropdown state=floating
bspc rule -a Pavucontrol state=floating center=true rectangle=520x300+0+0

# Set background with feh
feh --bg-fill ~/Pictures/whiterun.jpg &

# Start picom for transparency
picom &

# polybar launch script; kills all open polybars and starts main bar
zsh ~/.config/polybar/launch.sh

# Enable tapping on trackpad
xinput set-prop 12 319 1

numlockx &
