#! /usr/bin/bash

# Read from stdin
input=$(</dev/stdin)

# Convert to html w/ pandoc and copy to windows clipboard as html (pasting in teams, outlook, etc)
echo "$input" | pandoc --ascii | clip.exe | powershell.exe -command "get-clipboard | set-clipboard -ashtml"

# Echo back original contents to prevent deleting content when used in vim
echo "$input"
