#!/bin/bash

variety &

picom &

ID=$(xinput | grep "Synaptics" | cut -f2 | cut -d "=" -f2)
PROP="$(xinput list-props 12 | grep -E "Tapping Enabled \([[:digit:]]+\)" | grep -o -E "[[:digit:]]{3}+")"
xinput set-prop $ID $PROP 1

numlockx &

# Redshift geolocation using geoclue2
# Enable geoclue agent
# /usr/lib/geoclue-2.0/demos/agent &
