#! /bin/bash

ACCOUNT=$1
USER="$(whoami)"
MBSYNCDIR="/home/$USER/.cache/mbsync/"

mbsync -a
for ACC in $(ls $MBSYNCDIR); do
  NEWMESSAGES=$(ls "$MBSYNCDIR/$ACC/INBOX/new" | wc -l)
  if (( NEWMESSAGES > 0 )); then
    dunstify --icon="/home/$USER/.config/mutt/mutt-logo.png" "New Messages for $ACC: $NEWMESSAGES"
  fi
done
