#! /bin/bash

ACCOUNT=$1
USER="$(whoami)"
MBSYNCDIR="/home/$USER/.cache/mbsync/$ACCOUNT/INBOX/new"

mbsync -a
NEWMESSAGES=$(ls "$MBSYNCDIR" | wc -l)
if (( NEWMESSAGES > 0 )); then
  dunstify --icon="/home/$USER/.config/mutt/mutt-logo.png" "New Messages: $NEWMESSAGES"
fi

# Loop for continual syncing
# while true; do
# 
#   mbsync "$ACCOUNT"
#   NEWMESSAGES=$(ls "$MBSYNCDIR" | wc -l)
#   if (( NEWMESSAGES > 0 )); then
#     dunstify --icon="/home/$USER/.config/mutt/mutt-logo.png" "New Messages: $NEWMESSAGES"
#   fi
#   sleep 1m
# done
